#ifndef ULTRASONIC_CONFIG_H
#define ULTRASONIC_CONFIG_H

#define ULTRA_SONIC_TRIG_PORT   PORTA
#define ULTRA_SONIC_ECHO_PORT   PORTD

#define ULTRA_SONIC_TRIG_PIN    PIN0
#define ULTRA_SONIC_ECHO_PIN    PIN6


#endif
